plugins {
    id 'fabric-loom' version '1.11.3'
    id 'maven-publish'
}

version = ""
group = project.maven_group

base {
    archivesName = "mcc-1.0-dev"
}

repositories {
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings "net.fabricmc:yarn:${project.yarn_mappings}:v2"
    modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"
}

processResources {
    inputs.property "version", "1.0.0"
    filesMatching("fabric.mod.json") {
        expand "version": "1.0.0"
    }
}

tasks.withType(JavaCompile).configureEach {
    it.options.encoding = "UTF-8"
    it.options.release = 21
}

java {
    withSourcesJar()
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

jar {
    archiveFileName = "mcc-1.0-dev.jar" // 强制指定输出文件名
    from("LICENSE") {
        rename { "${it}_${project.archives_base_name}" }
    }
}

// 确保 dev jar 不会有额外的 -dev 后缀
tasks.named('sourcesJar') {
    archiveFileName = "mcc-1.0-dev-sources.jar"
}
